#!/bin/bash

# Change these four parameters as needed for your own environment
AKS_PERS_STORAGE_ACCOUNT_NAME=chaosstorage
AKS_PERS_RESOURCE_GROUP=chaoskreuzung

# Get storage account key
STORAGE_KEY=$(az storage account keys list --resource-group $AKS_PERS_RESOURCE_GROUP --account-name $AKS_PERS_STORAGE_ACCOUNT_NAME --query "[0].value" -o tsv)

# Echo storage account name and key
echo Storage account name: $AKS_PERS_STORAGE_ACCOUNT_NAME
echo Storage account key: $STORAGE_KEY

kubectl delete secret cvat-backend-record-secret -n cvat
kubectl create secret generic cvat-backend-record-secret --from-literal=azurestorageaccountname=$AKS_PERS_STORAGE_ACCOUNT_NAME --from-literal=azurestorageaccountkey=$STORAGE_KEY -n cvat